version: '3'
volumes:
  postgres_data:
      driver: local
services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  keycloak:
      image: quay.io/keycloak/keycloak
      command: start
      environment:
        KC_PROXY: ${KC_PROXY}
        KC_HOSTNAME: ${KC_HOSTNAME}
        KC_DB: ${KC_DB}
        KC_DB_ADDR: ${KC_DB_ADDR}
        KC_DB_URL: ${KC_DB_URL}
        KC_DB_USER: ${KC_DB_USER}
        KC_DB_SCHEMA: ${KC_DB_SCHEMA}
        KC_DB_PASSWORD: ${KC_DB_PASSWORD}
        KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
        KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      ports:
        - 8033:8080
      depends_on:
        - postgres